name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Static Code Analysis
        run: npm run lint

      - name: Build Docker image
        run: docker build -t sample-app-devops .

      - name: Scan Docker image
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: sample-app-devops

      - name: Docker tag the image
        run: docker tag sample-app-devops odilo1/sample-app-devops:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sample-app-devops:latest
